name: Test and Deploy to DigitalOcean Spaces

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Install dependencies
      run: npm ci

    - name: Get pricing data for Droplets
      env:
        TYPE: droplets
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      run: ./ci/get-pricing-data.sh

    - name: Get pricing data for Kubernetes
      env:
        TYPE: kubernetes
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      run: ./ci/get-pricing-data.sh

    - name: Test and build
      run: |
        npm test
        npm run build

    - name: Include pricing data
      run: |
        cp build/droplets.json dist/droplets.json
        cp build/kubernetes.json dist/kubernetes.json

    - name: Debug output
      run: |
        ls dist
        cat dist/droplets.json
        cat dist/kubernetes.json

    - name: Deploy commit to DigitalOcean Spaces
      run: aws s3 sync ./dist s3://${{ secrets.SPACES_BUCKET }}/commits/bandwidth-tool/${{ github.sha }} --endpoint=https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com --acl public-read --content-encoding utf8
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SPACES_REGION }}

    - name: Leave a comment
      run: npm run deploy:spaces:comment
      env:
        REPO_NAME: ${{ github.repository }}
        COMMIT_SHA: ${{ github.sha }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SPACES_REGION: ${{ secrets.SPACES_REGION }}
        SPACES_BUCKET: ${{ secrets.SPACES_BUCKET }}
